// Code generated by "audit_policy.go" DO NOT EDIT.

package hooks

//var systemNamespaces = []string{"kube-system", "d8-cert-manager", "d8-chrony", "d8-cloud-instance-manager", "d8-cloud-provider-aws", "d8-cloud-provider-azure", "d8-cloud-provider-gcp", "d8-cloud-provider-openstack", "d8-cloud-provider-vsphere", "d8-cloud-provider-yandex", "d8-cni-flannel", "d8-cni-simple-bridge", "d8-descheduler", "d8-flant-integration", "d8-ingress-nginx", "d8-istio", "d8-keepalived", "d8-local-path-provisioner", "d8-log-shipper", "d8-metallb", "d8-monitoring", "d8-network-gateway", "d8-okmeter", "d8-openvpn", "d8-operator-prometheus", "d8-pod-reloader", "d8-system", "d8-user-authn", "d8-user-authz"}
//var systemSA = []string{"system:serviceaccount:d8-system:deckhouse"}
